"""Tests for the Python codegen driver (replaces the archive's Gradle tasks).

These are integration-ish: they need the archive sources + clang present, and
are skipped if the archive is absent.
"""

import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from bp2cmake.codegen import (
    CodegenConfig, gen_operator_out, gen_mterp, gen_asm_defines,
)

# Pure multipath: foundational native sources live under nested vendor/.
# Historical absolute MinDalvikVM-Archive paths are intentionally not required.
_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
NATIVE = os.path.join(_REPO, "vendor")
# art/* codegen inputs come from the bumped vendor art tree (android-16.0.0_r4),
# matching the real build (native/CMakeLists.txt passes --art-root vendor).
ART_ROOT = os.path.join(_REPO, "vendor")
HAVE_ARCHIVE = os.path.isdir(NATIVE) and os.path.isdir(os.path.join(NATIVE, "libbase"))
HAVE_ART = os.path.isdir(os.path.join(ART_ROOT, "art"))
HAVE_CLANG = shutil.which("clang++") is not None


def _cfg(tmp):
    return CodegenConfig(native_root=NATIVE, gensrc_dir=tmp, arch="x86_64",
                         art_root=ART_ROOT)


def test_operator_out():
    if not (HAVE_ARCHIVE and HAVE_ART):
        return
    with tempfile.TemporaryDirectory() as tmp:
        outs = gen_operator_out(_cfg(tmp), "art/libartbase",
                                ["arch/instruction_set.h"])
        assert len(outs) == 1
        assert os.path.exists(outs[0])
        text = open(outs[0]).read()
        # generated operator<< for the InstructionSet enum
        assert "operator<<" in text
        assert "InstructionSet" in text
        # the #include is computed relative to the module reldir
        assert '#include "arch/instruction_set.h"' in text


def test_mterp():
    if not (HAVE_ARCHIVE and HAVE_ART):
        return
    with tempfile.TemporaryDirectory() as tmp:
        out = gen_mterp(_cfg(tmp), "x86_64")
        assert os.path.exists(out)
        text = open(out).read()
        assert "generated by gen-mterp.py" in text
        assert len(text.splitlines()) > 1000   # substantial generated asm


def test_aconfig():
    if not HAVE_ART:
        return
    from bp2cmake.codegen import gen_aconfig
    with tempfile.TemporaryDirectory() as tmp:
        outs = gen_aconfig(_cfg(tmp))
        assert len(outs) == 2
        joined = "\n".join(open(o).read() for o in outs)
        # read-only flag -> constexpr + uppercase macro (thread.h needs both).
        assert "inline constexpr bool virtual_thread_impl_v1()" in joined
        assert "#define COM_ANDROID_ART_FLAGS_VIRTUAL_THREAD_IMPL_V1" in joined
        # the C accessor flags.cc calls.
        assert "bool com_android_art_rw_flags_test_rw_flag()" in joined


def test_asm_defines():
    if not (HAVE_ART and HAVE_CLANG):
        return
    with tempfile.TemporaryDirectory() as tmp:
        from bp2cmake.codegen import gen_aconfig
        gen_aconfig(_cfg(tmp))  # asm_defines.cc may include aconfig headers
        out = gen_asm_defines(_cfg(tmp))
        assert os.path.exists(out)
        defines = [l for l in open(out).read().splitlines() if l.startswith("#define")]
        # The two-stage pipeline should find ~188 asm defines.
        assert len(defines) > 100
        # spot-check a known constant is present
        assert any("ACCESS_FLAGS_CLASS_IS_INTERFACE" in d for d in defines)
