# Generated by bp2cmake from cc_library "liblog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(log SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_list.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_name.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_read.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/properties.cpp
)

target_include_directories(log
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(log
        PRIVATE -Wall -Wextra -Wexit-time-destructors -DLIBLOG_LOG_TAG=1006 -DSNET_EVENT_LOG_TAG=1397638484 -DANDROID_DEBUGGABLE=0
)

# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)

# Generated by bp2cmake from art_cc_library "libartpalette". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(artpalette SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/system/palette_fake.cc
)

target_include_directories(artpalette
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(artpalette
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(artpalette base log)

# Generated by bp2cmake from cc_library "libziparchive". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(ziparchive SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive_stream_entry.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_cd_entry_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_error.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_writer.cc
)

target_include_directories(ziparchive
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/incfs_support/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_COMPAT_INCLUDE_DIR}
)

target_compile_options(ziparchive
        PRIVATE -DZLIB_CONST -Wall -D_FILE_OFFSET_BITS=64 -DINCFS_SUPPORT_DISABLED=1
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++2a -Wno-missing-field-initializers -Wconversion -Wno-sign-conversion -Wold-style-cast>
)

target_link_libraries(ziparchive base log z)

# Generated by bp2cmake from art_cc_library "libartbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/arch/instruction_set.h > ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: arch/instruction_set.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/allocator.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/allocator.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/unix_file/fd_file.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/unix_file/fd_file.h"
    VERBATIM)

add_library(artbase SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/compiler_filter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/enums.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_magic.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/flags.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/hex_dump.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/logging.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/malloc_arena_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/membarrier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memfd.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memory_region.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/metrics/metrics_common.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/os_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/runtime_debug.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/safe_copy.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_flock.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/socket_peer_is_trusted.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/time_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/random_access_file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/globals_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
        ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
)

target_include_directories(artbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(artbase
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(artbase
        PUBLIC ART_STACK_OVERFLOW_GAP_arm=8192 ART_STACK_OVERFLOW_GAP_arm64=8192 ART_STACK_OVERFLOW_GAP_riscv64=8192 ART_STACK_OVERFLOW_GAP_x86=8192 ART_STACK_OVERFLOW_GAP_x86_64=8192 ART_FRAME_SIZE_LIMIT=1736
)

target_link_libraries(artbase ziparchive z log artpalette base cap)

# Generated by bp2cmake from art_cc_library "libdexfile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file_layout.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file_layout.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction_utils.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction_utils.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction_utils.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/invoke_type.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/invoke_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/invoke_type.h"
    VERBATIM)

add_library(dexfile SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/art_dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_offset_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/descriptors_names.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_exception_helpers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_tracking_registrar.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_verifier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/modifiers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/primitive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/signature.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/standard_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/type_lookup_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/utf.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/dex_file_ext.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
)

target_include_directories(dexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(dexfile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(dexfile ziparchive z artpalette log base artbase)
