// Generated by bp2cmake.aconfig (host aconfig stand-in). Do not edit.
// Source: com.android.art.flags aconfig declarations.
#ifndef COM_ANDROID_ART_FLAGS_H_
#define COM_ANDROID_ART_FLAGS_H_

#define COM_ANDROID_ART_FLAGS_USE_GENERATIONAL_CMC false
#define COM_ANDROID_ART_FLAGS_ALWAYS_ENABLE_PROFILE_CODE false
#define COM_ANDROID_ART_FLAGS_REG_ALLOC_SPILL_SLOT_REUSE false
#define COM_ANDROID_ART_FLAGS_REG_ALLOC_NO_OUTPUT_OVERLAP false
#define COM_ANDROID_ART_FLAGS_WEAK_CONST_STRING false
#define COM_ANDROID_ART_FLAGS_TEST false
#define COM_ANDROID_ART_FLAGS_EXECUTABLE_METHOD_FILE_OFFSETS false
#define COM_ANDROID_ART_FLAGS_EXECUTABLE_METHOD_FILE_OFFSETS_DEPRECATION false
#define COM_ANDROID_ART_FLAGS_EXECUTABLE_METHOD_FILE_OFFSETS_V2 false
#define COM_ANDROID_ART_FLAGS_ART_SERVICE_V3 false
#define COM_ANDROID_ART_FLAGS_VIRTUAL_THREAD_IMPL_V1 false
#define COM_ANDROID_ART_FLAGS_FAST_BASELINE_COMPILER false
#define COM_ANDROID_ART_FLAGS_ENFORCE_PERMITTED_SUBCLASSES_CHECKS false
#define COM_ANDROID_ART_FLAGS_UPDATABLE_FILTER_AND_REASON false
#define COM_ANDROID_ART_FLAGS_IGNORE_BOOT_IMAGE_EXTENSION_CLASS_RESOLUTION false
#define COM_ANDROID_ART_FLAGS_DEXOPT_SECONDARY_ISA_ONLY_WHEN_NEEDED false
#define COM_ANDROID_ART_FLAGS_ART_MANAGED_INSTALL_FILES_VALIDATION_API false
#define COM_ANDROID_ART_FLAGS_HIDDENAPI_JNI_API_CALLERS false
#define COM_ANDROID_ART_FLAGS_HIDDENAPI_PLATFORM_ENFORCEMENT false
#define COM_ANDROID_ART_FLAGS_PACKAGE_LAST_USED_API false

#ifdef __cplusplus
namespace com { namespace android { namespace art { namespace flags { 
inline constexpr bool use_generational_cmc() { return false; }
inline constexpr bool always_enable_profile_code() { return false; }
inline constexpr bool reg_alloc_spill_slot_reuse() { return false; }
inline constexpr bool reg_alloc_no_output_overlap() { return false; }
inline constexpr bool weak_const_string() { return false; }
inline constexpr bool test() { return false; }
inline constexpr bool executable_method_file_offsets() { return false; }
inline constexpr bool executable_method_file_offsets_deprecation() { return false; }
inline constexpr bool executable_method_file_offsets_v2() { return false; }
inline constexpr bool art_service_v3() { return false; }
inline constexpr bool virtual_thread_impl_v1() { return false; }
inline constexpr bool fast_baseline_compiler() { return false; }
inline constexpr bool enforce_permitted_subclasses_checks() { return false; }
inline constexpr bool updatable_filter_and_reason() { return false; }
inline constexpr bool ignore_boot_image_extension_class_resolution() { return false; }
inline constexpr bool dexopt_secondary_isa_only_when_needed() { return false; }
inline constexpr bool art_managed_install_files_validation_api() { return false; }
inline constexpr bool hiddenapi_jni_api_callers() { return false; }
inline constexpr bool hiddenapi_platform_enforcement() { return false; }
inline constexpr bool package_last_used_api() { return false; }
}}}}  // com::android::art::flags
#endif  // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif
inline bool com_android_art_flags_use_generational_cmc() { return false; }
inline bool com_android_art_flags_always_enable_profile_code() { return false; }
inline bool com_android_art_flags_reg_alloc_spill_slot_reuse() { return false; }
inline bool com_android_art_flags_reg_alloc_no_output_overlap() { return false; }
inline bool com_android_art_flags_weak_const_string() { return false; }
inline bool com_android_art_flags_test() { return false; }
inline bool com_android_art_flags_executable_method_file_offsets() { return false; }
inline bool com_android_art_flags_executable_method_file_offsets_deprecation() { return false; }
inline bool com_android_art_flags_executable_method_file_offsets_v2() { return false; }
inline bool com_android_art_flags_art_service_v3() { return false; }
inline bool com_android_art_flags_virtual_thread_impl_v1() { return false; }
inline bool com_android_art_flags_fast_baseline_compiler() { return false; }
inline bool com_android_art_flags_enforce_permitted_subclasses_checks() { return false; }
inline bool com_android_art_flags_updatable_filter_and_reason() { return false; }
inline bool com_android_art_flags_ignore_boot_image_extension_class_resolution() { return false; }
inline bool com_android_art_flags_dexopt_secondary_isa_only_when_needed() { return false; }
inline bool com_android_art_flags_art_managed_install_files_validation_api() { return false; }
inline bool com_android_art_flags_hiddenapi_jni_api_callers() { return false; }
inline bool com_android_art_flags_hiddenapi_platform_enforcement() { return false; }
inline bool com_android_art_flags_package_last_used_api() { return false; }
#ifdef __cplusplus
}
#endif

#endif  // COM_ANDROID_ART_FLAGS_H_
