// Generated by bp2cmake.aconfig (host aconfig stand-in). Do not edit.
// Source: com.android.art.rw.flags aconfig declarations.
#ifndef COM_ANDROID_ART_RW_FLAGS_H_
#define COM_ANDROID_ART_RW_FLAGS_H_


#ifdef __cplusplus
namespace com { namespace android { namespace art { namespace rw { namespace flags { 
inline bool test_rw_flag() { return false; }
inline bool use_uffd_move_ioctl_cmc_gc() { return false; }
inline bool enable_time_based_gc_triggering() { return false; }
inline bool auto_tune_time_based_gc_triggering() { return false; }
inline bool post_ur_job() { return false; }
inline bool assume_value_sdk_int() { return false; }
inline bool enable_profile_code_rw() { return false; }
inline bool madvise_type_lookup_table() { return false; }
inline bool pm_compile_verbose_logging() { return false; }
inline bool read_only_dynamic_code_load_ww_log() { return false; }
inline bool read_only_dynamic_code_load_throw_exception() { return false; }
}}}}}  // com::android::art::rw::flags
#endif  // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif
inline bool com_android_art_rw_flags_test_rw_flag() { return false; }
inline bool com_android_art_rw_flags_use_uffd_move_ioctl_cmc_gc() { return false; }
inline bool com_android_art_rw_flags_enable_time_based_gc_triggering() { return false; }
inline bool com_android_art_rw_flags_auto_tune_time_based_gc_triggering() { return false; }
inline bool com_android_art_rw_flags_post_ur_job() { return false; }
inline bool com_android_art_rw_flags_assume_value_sdk_int() { return false; }
inline bool com_android_art_rw_flags_enable_profile_code_rw() { return false; }
inline bool com_android_art_rw_flags_madvise_type_lookup_table() { return false; }
inline bool com_android_art_rw_flags_pm_compile_verbose_logging() { return false; }
inline bool com_android_art_rw_flags_read_only_dynamic_code_load_ww_log() { return false; }
inline bool com_android_art_rw_flags_read_only_dynamic_code_load_throw_exception() { return false; }
#ifdef __cplusplus
}
#endif

#endif  // COM_ANDROID_ART_RW_FLAGS_H_
