# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)
