# Generated by bp2cmake from cc_library "liblog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(log SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_list.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_name.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_read.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/properties.cpp
)

target_include_directories(log
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(log
        PRIVATE -Wall -Wextra -Wexit-time-destructors -DLIBLOG_LOG_TAG=1006 -DSNET_EVENT_LOG_TAG=1397638484 -DANDROID_DEBUGGABLE=0
)

# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)

# Generated by bp2cmake from art_cc_library "libartpalette". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(artpalette SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/system/palette_fake.cc
)

target_include_directories(artpalette
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(artpalette
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(artpalette base log)
