# Generated by bp2cmake from cc_library "liblog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(log SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_list.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_name.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_read.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/properties.cpp
)

target_include_directories(log
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(log
        PRIVATE -Wall -Wextra -Wexit-time-destructors -DLIBLOG_LOG_TAG=1006 -DSNET_EVENT_LOG_TAG=1397638484 -DANDROID_DEBUGGABLE=0
)

# Generated by bp2cmake from cc_library_shared "libnativehelper". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativehelper SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/DlHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/ExpandableString.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIPlatformHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniConstants.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniInvocation.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/file_descriptor_jni.c
)

target_include_directories(nativehelper
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform_header_only
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(nativehelper
        PRIVATE -fvisibility=protected -std=c11
)

target_link_libraries(nativehelper log)

# Generated by bp2cmake from cc_library "libprocinfo". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(procinfo SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/process.cpp
)

target_include_directories(procinfo
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
)

target_compile_options(procinfo
        PRIVATE -Wall -Wextra
)

target_link_libraries(procinfo base)

# Generated by bp2cmake from cc_library "libziparchive". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(ziparchive SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive_stream_entry.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_cd_entry_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_error.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_writer.cc
)

target_include_directories(ziparchive
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/incfs_support/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(ziparchive
        PRIVATE -DZLIB_CONST -Wall -D_FILE_OFFSET_BITS=64 -DINCFS_SUPPORT_DISABLED=1
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++2a -Wno-missing-field-initializers -Wconversion -Wno-sign-conversion -Wold-style-cast>
)

target_link_libraries(ziparchive base log z)

# Generated by bp2cmake from cc_library "libtinyxml2". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(tinyxml2 SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
)

target_include_directories(tinyxml2
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(tinyxml2
        PRIVATE -Wall -Wno-implicit-fallthrough
)

# Generated by bp2cmake from cc_library "liblzma". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(lzma SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zAlloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zArcIn.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrcOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zFile.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zStream.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Aes.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/AesOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Alloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bcj2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra86.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/BraIA64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/CpuArch.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Delta.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzFind.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaLib.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sha256.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sort.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Xz.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64Opt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzIn.c
)

target_include_directories(lzma
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
)

target_compile_options(lzma
        PRIVATE -D_7ZIP_ST -Wall -Wno-empty-body -Wno-enum-conversion -Wno-logical-op-parentheses -Wno-self-assign
)

# Generated by bp2cmake from cc_library "libcpu_features". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(cpu_features STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/impl_x86_linux_or_android.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
)

target_include_directories(cpu_features
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/include
)

target_compile_options(cpu_features
        PRIVATE -DSTACK_LINE_READER_BUFFER_SIZE=1024 -Wno-gnu-designator -Wno-unused-variable
)

target_compile_definitions(cpu_features
        PRIVATE HAVE_STRONG_GETAUXVAL HAVE_DLFCN_H
)

# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)
