# Generated by bp2cmake from cc_library "liblog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(log SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_list.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_name.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_read.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/properties.cpp
)

target_include_directories(log
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(log
        PRIVATE -Wall -Wextra -Wexit-time-destructors -DLIBLOG_LOG_TAG=1006 -DSNET_EVENT_LOG_TAG=1397638484 -DANDROID_DEBUGGABLE=0
)

# Generated by bp2cmake from cc_library_shared "libnativehelper". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativehelper SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/DlHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/ExpandableString.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIPlatformHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniConstants.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniInvocation.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/file_descriptor_jni.c
)

target_include_directories(nativehelper
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform_header_only
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(nativehelper
        PRIVATE -fvisibility=protected -std=c11
        PRIVATE $<$<COMPILE_LANGUAGE:C>:-std=gnu11>
)

target_link_libraries(nativehelper log)

# Generated by bp2cmake from cc_library "libprocinfo". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(procinfo SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/process.cpp
)

target_include_directories(procinfo
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
)

target_compile_options(procinfo
        PRIVATE -Wall -Wextra
)

target_link_libraries(procinfo base)

# Generated by bp2cmake from cc_library "libtinyxml2". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(tinyxml2 SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
)

target_include_directories(tinyxml2
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(tinyxml2
        PRIVATE -Wall -Wno-implicit-fallthrough
)

# Generated by bp2cmake from cc_library "liblzma". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(lzma SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zAlloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zArcIn.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrcOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zFile.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zStream.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Aes.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/AesOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Alloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bcj2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra86.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/BraIA64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/CpuArch.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Delta.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzFind.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaLib.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sha256.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sort.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Xz.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64Opt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzIn.c
)

target_include_directories(lzma
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
)

target_compile_options(lzma
        PRIVATE -D_7ZIP_ST -Wall -Wno-empty-body -Wno-enum-conversion -Wno-logical-op-parentheses -Wno-self-assign
)

# Generated by bp2cmake from cc_library "libcpu_features". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(cpu_features STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/impl_x86_linux_or_android.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
)

target_include_directories(cpu_features
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/include
)

target_compile_options(cpu_features
        PRIVATE -DSTACK_LINE_READER_BUFFER_SIZE=1024 -Wno-gnu-designator -Wno-unused-variable
)

target_compile_definitions(cpu_features
        PRIVATE HAVE_STRONG_GETAUXVAL HAVE_DLFCN_H
)

# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)

# Generated by bp2cmake from art_cc_library "libartpalette". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(artpalette SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/system/palette_fake.cc
)

target_include_directories(artpalette
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(artpalette
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(artpalette base log)

# Generated by bp2cmake from cc_library "libziparchive". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(ziparchive SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive_stream_entry.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_cd_entry_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_error.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_writer.cc
)

target_include_directories(ziparchive
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/incfs_support/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_COMPAT_INCLUDE_DIR}
)

target_compile_options(ziparchive
        PRIVATE -DZLIB_CONST -Wall -D_FILE_OFFSET_BITS=64 -DINCFS_SUPPORT_DISABLED=1
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++2a -Wno-missing-field-initializers -Wconversion -Wno-sign-conversion -Wold-style-cast>
)

target_link_libraries(ziparchive base log z)

# Generated by bp2cmake from art_cc_library "libartbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/arch/instruction_set.h > ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: arch/instruction_set.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/allocator.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/allocator.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/unix_file/fd_file.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/unix_file/fd_file.h"
    VERBATIM)

add_library(artbase SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/compiler_filter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/enums.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_magic.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/flags.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/hex_dump.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/logging.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/malloc_arena_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/membarrier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memfd.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memory_region.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/metrics/metrics_common.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/os_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/runtime_debug.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/safe_copy.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_flock.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/socket_peer_is_trusted.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/time_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/random_access_file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/globals_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
        ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
)

target_include_directories(artbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(artbase
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(artbase
        PUBLIC ART_STACK_OVERFLOW_GAP_arm=8192 ART_STACK_OVERFLOW_GAP_arm64=8192 ART_STACK_OVERFLOW_GAP_riscv64=8192 ART_STACK_OVERFLOW_GAP_x86=8192 ART_STACK_OVERFLOW_GAP_x86_64=8192 ART_FRAME_SIZE_LIMIT=1736
)

target_link_libraries(artbase ziparchive z log artpalette base cap)

# Generated by bp2cmake from art_cc_library "libdexfile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file_layout.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file_layout.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction_utils.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction_utils.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction_utils.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/invoke_type.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/invoke_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/invoke_type.h"
    VERBATIM)

add_library(dexfile SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/art_dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_offset_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/descriptors_names.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_exception_helpers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_tracking_registrar.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_verifier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/modifiers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/primitive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/signature.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/standard_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/type_lookup_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/utf.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/dex_file_ext.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
)

target_include_directories(dexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(dexfile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(dexfile ziparchive z artpalette log base artbase)

# Generated by bp2cmake from art_cc_library_static "libelffile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(elffile STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/elf/xz_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/buffered_output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/file_output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/vector_output_stream.cc
)

target_include_directories(elffile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(elffile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86 -fPIC
)

target_link_libraries(elffile base lzma artbase)

# Generated by bp2cmake from art_cc_library "libprofile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(profile SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile/profile/profile_boot_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile/profile/profile_compilation_info.cc
)

target_include_directories(profile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
)

target_compile_options(profile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(profile artpalette ziparchive z base artbase dexfile)

# Generated by bp2cmake from cc_library "libsigchain". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(sigchain SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib/sigchain.cc
)

target_include_directories(sigchain
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib
)

target_compile_options(sigchain
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(sigchain
        PRIVATE CHAR_BIT=8
)

target_link_options(sigchain PRIVATE -Wl,-z,global)

# Generated by bp2cmake from art_cc_library "libnativebridge". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativebridge SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/native_bridge.cc
)

target_include_directories(nativebridge
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(nativebridge
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(nativebridge log)

# Generated by bp2cmake from art_cc_library "libnativeloader". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativeloader SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativeloader/native_loader.cpp
)

target_include_directories(nativeloader
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativeloader/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/include
)

target_compile_options(nativeloader
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(nativeloader log nativebridge base)

# Generated by bp2cmake from cc_library_static "libodrstatslog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(odrstatslog STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/odrefresh/odr_statslog_host.cc
)

target_include_directories(odrstatslog
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/odrefresh/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(odrstatslog
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86 -fPIC
)

target_link_libraries(odrstatslog artbase)

# Generated by bp2cmake from cc_library "libunwindstack". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(unwindstack SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/AndroidUnwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ArmExidx.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Demangle.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DexFiles.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfCfa.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfEhFrameWithHdr.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfMemory.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfOp.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfSection.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Elf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ElfInterface.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ElfInterfaceArm.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Global.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/JitDebug.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MapInfo.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Maps.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Memory.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MemoryMte.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MemoryXz.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Regs.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsArm.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsArm64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsX86.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsX86_64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsRiscv64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsMips.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsMips64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Symbols.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ThreadEntry.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ThreadUnwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Unwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DexFile.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/LogAndroid.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/AsmGetRegsX86_64.S
)

target_include_directories(unwindstack
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/include
)

target_compile_options(unwindstack
        PRIVATE -Wall -Wextra -Wexit-time-destructors -fno-c++-static-destructors -DDEXFILE_SUPPORT -O0 -g
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=gnu++20>
)

target_link_libraries(unwindstack base log lzma dexfile procinfo)
