"""aconfig C++ header generator (host stand-in for AOSP's `aconfig` tool).

android-16.0.0_r4 introduced Android's aconfig feature-flag system into ART.
libartbase/base/flags.cc and code across runtime/ + compiler/ include the
GENERATED headers `com_android_art_flags.h` and `com_android_art_rw_flags.h`
and call `com::android::art::flags::<flag>()` etc. Those headers are produced on
Android by the Rust `aconfig` tool from the `.aconfig` declaration files; we
don't have that tool, so this module reproduces aconfig's C++ codegen for our
host build, reading the same `.aconfig` sources so it stays correct across bumps.

Output matches aconfig's C++ `production`/`exported` mode closely enough for ART:

  * read-only flags (`is_fixed_read_only: true`): emitted as `constexpr bool
    <flag>()` in the package namespace PLUS a `#define
    COM_ANDROID_ART_FLAGS_<FLAG>` bool-literal macro (ART uses both, e.g.
    thread.h's `static_assert(...::virtual_thread_impl_v1() == COM_..._V1)`).
  * read-write flags: emitted as a plain `inline bool <flag>()` (no constexpr,
    no compile-time macro) since their value would normally come from
    server-side config; here it is the baked default.
  * C-style accessors `com_android_art[_rw]_flags_<flag>()` (flags.cc calls
    `com_android_art_rw_flags_test_rw_flag()`).

Default value: a flag with no `state: ENABLED` defaults to DISABLED (false).
None of ART's `.aconfig` flags declare an enabled default, so every flag is
false -- i.e. a build with no flag overrides, the behavior-preserving choice.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass


@dataclass
class Flag:
    name: str
    read_only: bool   # is_fixed_read_only: true
    enabled: bool      # state: ENABLED (default DISABLED -> False)


@dataclass
class AconfigPackage:
    package: str                 # e.g. "com.android.art.flags"
    flags: list[Flag]

    @property
    def namespace(self) -> str:
        return "::".join(self.package.split("."))

    @property
    def c_prefix(self) -> str:
        return self.package.replace(".", "_")

    @property
    def header_name(self) -> str:
        return self.c_prefix + ".h"

    @property
    def macro_prefix(self) -> str:
        return self.c_prefix.upper()


_FLAG_RE = re.compile(r"\bflag\s*\{(.*?)\}", re.DOTALL)


def parse_aconfig(text: str) -> AconfigPackage:
    # package: "..."  (strip comments first so '#'-comments don't swallow it)
    no_comments = "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("#")
    )
    pkg_m = re.search(r'package:\s*"([^"]+)"', no_comments)
    package = pkg_m.group(1) if pkg_m else "unknown"
    flags: list[Flag] = []
    for block in _FLAG_RE.findall(no_comments):
        name_m = re.search(r'name:\s*"([^"]+)"', block)
        if not name_m:
            continue
        name = name_m.group(1)
        ro_m = re.search(r"is_fixed_read_only:\s*(true|false)", block)
        read_only = bool(ro_m and ro_m.group(1) == "true")
        state_m = re.search(r"state:\s*(\w+)", block)
        enabled = bool(state_m and state_m.group(1) == "ENABLED")
        flags.append(Flag(name=name, read_only=read_only, enabled=enabled))
    return AconfigPackage(package=package, flags=flags)


def render_header(pkg: AconfigPackage) -> str:
    guard = pkg.macro_prefix + "_H_"
    ns_open = "".join(f"namespace {p} {{ " for p in pkg.package.split("."))
    ns_close = "}" * len(pkg.package.split("."))
    L: list[str] = []
    L.append("// Generated by bp2cmake.aconfig (host aconfig stand-in). Do not edit.")
    L.append(f"// Source: {pkg.package} aconfig declarations.")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append("")
    # Compile-time macros for read-only flags (aconfig emits these uppercase).
    for f in pkg.flags:
        if f.read_only:
            L.append(f"#define {pkg.macro_prefix}_{f.name.upper()} "
                     f"{'true' if f.enabled else 'false'}")
    L.append("")
    L.append("#ifdef __cplusplus")
    L.append(f"{ns_open}")
    for f in pkg.flags:
        val = "true" if f.enabled else "false"
        if f.read_only:
            L.append(f"inline constexpr bool {f.name}() {{ return {val}; }}")
        else:
            L.append(f"inline bool {f.name}() {{ return {val}; }}")
    L.append(f"{ns_close}  // {pkg.namespace}")
    L.append("#endif  // __cplusplus")
    L.append("")
    # C-style accessors (extern "C"-safe).
    L.append("#ifdef __cplusplus")
    L.append('extern "C" {')
    L.append("#endif")
    for f in pkg.flags:
        val = "true" if f.enabled else "false"
        L.append(f"inline bool {pkg.c_prefix}_{f.name}() {{ return {val}; }}")
    L.append("#ifdef __cplusplus")
    L.append("}")
    L.append("#endif")
    L.append("")
    L.append(f"#endif  // {guard}")
    L.append("")
    return "\n".join(L)


def render_java(pkg: AconfigPackage) -> str:
    """Render the aconfig-generated Java `Flags` class for a package: one
    `public static final String FLAG_<NAME> = "<package>.<name>";` per flag,
    plus a camelCase `<name>()` accessor returning the (default == disabled)
    value. aconfig's Java codegen lower-camelCases the flag name for the
    accessor (e.g. virtual_thread_impl_v1 -> virtualThreadImplV1()), while the
    constant stays FLAG_<UPPER_SNAKE>. ART libcore uses both forms
    (`@FlaggedApi(<pkg>.Flags.FLAG_X)` and `Flags.someFlag()`)."""
    def camel(name: str) -> str:
        parts = name.split("_")
        return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])

    L: list[str] = []
    L.append(f"package {pkg.package};")
    L.append("")
    L.append("// Generated by bp2cmake.aconfig (host aconfig stand-in). Do not edit.")
    L.append("/** @hide */")
    L.append("public final class Flags {")
    for f in pkg.flags:
        const = "FLAG_" + f.name.upper()
        L.append(f'    public static final String {const} = "{pkg.package}.{f.name}";')
    L.append("")
    for f in pkg.flags:
        val = "true" if f.enabled else "false"
        L.append(f"    public static boolean {camel(f.name)}() {{ return {val}; }}")
    L.append("}")
    L.append("")
    return "\n".join(L)


def generate_java(aconfig_files: list[str], out_dir: str) -> list[str]:
    """Parse each .aconfig file and write its Java `Flags` class under
    out_dir/<package as dirs>/Flags.java. Returns written paths."""
    written: list[str] = []
    for path in aconfig_files:
        with open(path) as fh:
            pkg = parse_aconfig(fh.read())
        pkg_dir = os.path.join(out_dir, *pkg.package.split("."))
        os.makedirs(pkg_dir, exist_ok=True)
        out_path = os.path.join(pkg_dir, "Flags.java")
        with open(out_path, "w") as fh:
            fh.write(render_java(pkg))
        written.append(out_path)
    return written


def generate(aconfig_files: list[str], out_dir: str) -> list[str]:
    """Parse each .aconfig file and write its C++ header into out_dir.
    Returns the list of written header paths."""
    os.makedirs(out_dir, exist_ok=True)
    written: list[str] = []
    for path in aconfig_files:
        with open(path) as fh:
            pkg = parse_aconfig(fh.read())
        out_path = os.path.join(out_dir, pkg.header_name)
        with open(out_path, "w") as fh:
            fh.write(render_header(pkg))
        written.append(out_path)
    return written
