# Generated by bp2cmake from cc_library "liblog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(log SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_list.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/log_event_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_name.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_read.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/logger_write.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/properties.cpp
)

target_include_directories(log
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(log
        PRIVATE -Wall -Wextra -Wexit-time-destructors -DLIBLOG_LOG_TAG=1006 -DSNET_EVENT_LOG_TAG=1397638484 -DANDROID_DEBUGGABLE=0
)

# Generated by bp2cmake from cc_library_shared "libnativehelper". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativehelper SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/DlHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/ExpandableString.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JNIPlatformHelp.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniConstants.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/JniInvocation.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/file_descriptor_jni.c
)

target_include_directories(nativehelper
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform_header_only
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(nativehelper
        PRIVATE -fvisibility=protected -std=c11
        PRIVATE $<$<COMPILE_LANGUAGE:C>:-std=gnu11>
)

target_link_libraries(nativehelper log)

# Generated by bp2cmake from cc_library "libprocinfo". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(procinfo SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/process.cpp
)

target_include_directories(procinfo
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
)

target_compile_options(procinfo
        PRIVATE -Wall -Wextra
)

target_link_libraries(procinfo base)

# Generated by bp2cmake from cc_library "libtinyxml2". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(tinyxml2 SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
)

target_include_directories(tinyxml2
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(tinyxml2
        PRIVATE -Wall -Wno-implicit-fallthrough
)

# Generated by bp2cmake from cc_library "liblzma". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(lzma SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zAlloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zArcIn.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zBuf.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zCrcOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zFile.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/7zStream.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Aes.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/AesOpt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Alloc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bcj2.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra86.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Bra.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/BraIA64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/CpuArch.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Delta.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzFind.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma2Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Lzma86Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/LzmaLib.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Dec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Ppmd7Enc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sha256.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Sort.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/Xz.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzCrc64Opt.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzDec.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzEnc.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C/XzIn.c
)

target_include_directories(lzma
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
)

target_compile_options(lzma
        PRIVATE -D_7ZIP_ST -Wall -Wno-empty-body -Wno-enum-conversion -Wno-logical-op-parentheses -Wno-self-assign
)

# Generated by bp2cmake from cc_library "libcpu_features". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(cpu_features STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/impl_x86_linux_or_android.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
)

target_include_directories(cpu_features
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/include
)

target_compile_options(cpu_features
        PRIVATE -DSTACK_LINE_READER_BUFFER_SIZE=1024 -Wno-gnu-designator -Wno-unused-variable
)

target_compile_definitions(cpu_features
        PRIVATE HAVE_STRONG_GETAUXVAL HAVE_DLFCN_H
)

set_source_files_properties(
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
        PROPERTIES COMPILE_OPTIONS "-DSTACK_LINE_READER_BUFFER_SIZE=1024;-Wno-gnu-designator")

# Generated by bp2cmake from cc_library "libbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(base SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/abi_compatibility.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/chrono_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/cmsg.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/hex.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/logging.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/mapped_file.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsebool.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/parsenetaddress.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/posix_strerror_r.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/process.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/properties.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/stringprintf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/strings.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/threads.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/test_utils.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/errors_unix.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
)

target_include_directories(base
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(base
        PRIVATE -Wall -Wextra
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Wexit-time-destructors -Wno-deprecated-declarations>
)

target_compile_definitions(base
        PRIVATE _FILE_OFFSET_BITS=64
)

target_link_libraries(base log)

set_source_files_properties(
        ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/src/format.cc
        PROPERTIES COMPILE_OPTIONS "-fno-exceptions;-UNDEBUG")

# Generated by bp2cmake from art_cc_library "libartpalette". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(artpalette SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/system/palette_fake.cc
)

target_include_directories(artpalette
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(artpalette
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(artpalette base log)

# Generated by bp2cmake from cc_library "libziparchive". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(ziparchive SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_archive_stream_entry.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_cd_entry_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_error.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/zip_writer.cc
)

target_include_directories(ziparchive
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/incfs_support/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_COMPAT_INCLUDE_DIR}
)

target_compile_options(ziparchive
        PRIVATE -DZLIB_CONST -Wall -D_FILE_OFFSET_BITS=64 -DINCFS_SUPPORT_DISABLED=1
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++2a -Wno-missing-field-initializers -Wconversion -Wno-sign-conversion -Wold-style-cast>
)

target_link_libraries(ziparchive base log z)

# Generated by bp2cmake from art_cc_library "libartbase". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/arch/instruction_set.h > ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: arch/instruction_set.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/allocator.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/allocator.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libartbase
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libartbase art/libartbase/base/unix_file/fd_file.h > ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_libartbase_operator_srcs: base/unix_file/fd_file.h"
    VERBATIM)

add_library(artbase SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/arch/instruction_set.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/arena_bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/bit_vector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/compiler_filter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/enums.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_magic.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/flags.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/hex_dump.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/logging.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/malloc_arena_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/membarrier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memfd.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/memory_region.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/metrics/metrics_common.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/os_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/runtime_debug.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/safe_copy.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_arena_allocator.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/scoped_flock.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/socket_peer_is_trusted.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/time_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/fd_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/unix_file/random_access_file_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/zip_archive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/globals_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase/base/mem_map_unix.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
        ${MDVM_GENSRC_DIR}/art/libartbase/arch/instruction_set.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/allocator.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libartbase/base/unix_file/fd_file.h.operator_out.cc
)

target_include_directories(artbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2
)

target_compile_options(artbase
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(artbase
        PUBLIC ART_STACK_OVERFLOW_GAP_arm=8192 ART_STACK_OVERFLOW_GAP_arm64=8192 ART_STACK_OVERFLOW_GAP_riscv64=8192 ART_STACK_OVERFLOW_GAP_x86=8192 ART_STACK_OVERFLOW_GAP_x86_64=8192 ART_FRAME_SIZE_LIMIT=1736
)

target_link_libraries(artbase ziparchive z log artpalette base cap)

set_source_files_properties(
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/tinyxml2/tinyxml2.cpp
        PROPERTIES COMPILE_OPTIONS "-Wall;-Werror;-Wno-implicit-fallthrough")

# Generated by bp2cmake from art_cc_library "libdexfile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_file_layout.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_file_layout.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/dex_instruction_utils.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction_utils.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/dex_instruction_utils.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/libdexfile
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/libdexfile art/libdexfile/dex/invoke_type.h > ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/invoke_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs dexfile_operator_srcs: dex/invoke_type.h"
    VERBATIM)

add_library(dexfile SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/art_dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/compact_offset_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/descriptors_names.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_exception_helpers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_layout.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_loader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_tracking_registrar.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_file_verifier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/dex_instruction.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/modifiers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/primitive.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/signature.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/standard_dex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/type_lookup_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/dex/utf.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/dex_file_ext.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/dex_file_supp.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_file_layout.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/dex_instruction_utils.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/libdexfile/dex/invoke_type.h.operator_out.cc
)

target_include_directories(dexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(dexfile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(dexfile ziparchive z artpalette log base artbase)

# Generated by bp2cmake from art_cc_library_static "libelffile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(elffile STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/elf/xz_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/buffered_output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/file_output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/output_stream.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile/stream/vector_output_stream.cc
)

target_include_directories(elffile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(elffile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86 -fPIC
)

target_link_libraries(elffile base lzma artbase)

# Generated by bp2cmake from art_cc_library "libprofile". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(profile SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile/profile/profile_boot_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile/profile/profile_compilation_info.cc
)

target_include_directories(profile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libziparchive/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
)

target_compile_options(profile
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(profile artpalette ziparchive z base artbase dexfile)

# Generated by bp2cmake from cc_library "libsigchain". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(sigchain SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib/sigchain.cc
)

target_include_directories(sigchain
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib
)

target_compile_options(sigchain
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(sigchain
        PRIVATE CHAR_BIT=8
)

target_link_options(sigchain PRIVATE -Wl,-z,global)

# Generated by bp2cmake from art_cc_library "libnativebridge". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativebridge SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/native_bridge.cc
)

target_include_directories(nativebridge
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
)

target_compile_options(nativebridge
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(nativebridge log)

# Generated by bp2cmake from art_cc_library "libnativeloader". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(nativeloader SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativeloader/native_loader.cpp
)

target_include_directories(nativeloader
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativeloader/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/include
)

target_compile_options(nativeloader
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_link_libraries(nativeloader log nativebridge base)

# Generated by bp2cmake from cc_library_static "libodrstatslog". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(odrstatslog STATIC
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/odrefresh/odr_statslog_host.cc
)

target_include_directories(odrstatslog
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/odrefresh/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
)

target_compile_options(odrstatslog
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86 -fPIC
)

target_link_libraries(odrstatslog artbase)

# Generated by bp2cmake from cc_library "libunwindstack". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_library(unwindstack SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/AndroidUnwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ArmExidx.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Demangle.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DexFiles.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfCfa.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfEhFrameWithHdr.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfMemory.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfOp.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DwarfSection.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Elf.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ElfInterface.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ElfInterfaceArm.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Global.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/JitDebug.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MapInfo.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Maps.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Memory.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MemoryMte.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/MemoryXz.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Regs.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsArm.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsArm64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsX86.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsX86_64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsRiscv64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsMips.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/RegsMips64.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Symbols.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ThreadEntry.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/ThreadUnwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/Unwinder.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/DexFile.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/LogAndroid.cpp
        ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/AsmGetRegsX86_64.S
)

target_include_directories(unwindstack
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libprocinfo/include
)

target_compile_options(unwindstack
        PRIVATE -Wall -Wextra -Wexit-time-destructors -fno-c++-static-destructors -DDEXFILE_SUPPORT -O0 -g
        PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=gnu++20>
)

target_link_libraries(unwindstack base log lzma dexfile procinfo)

# Generated by bp2cmake from art_cc_library "libart". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/base/callee_save_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/base/callee_save_type.h > ${MDVM_GENSRC_DIR}/art/runtime/base/callee_save_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/callee_save_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: base/callee_save_type.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/base/locks.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/base/locks.h > ${MDVM_GENSRC_DIR}/art/runtime/base/locks.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/locks.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: base/locks.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/class_status.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/class_status.h > ${MDVM_GENSRC_DIR}/art/runtime/class_status.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/class_status.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: class_status.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/compilation_kind.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/compilation_kind.h > ${MDVM_GENSRC_DIR}/art/runtime/compilation_kind.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/compilation_kind.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: compilation_kind.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc_root.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc_root.h > ${MDVM_GENSRC_DIR}/art/runtime/gc_root.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc_root.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc_root.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/allocator_type.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/allocator_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/allocator_type.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator/rosalloc.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/allocator/rosalloc.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator/rosalloc.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/allocator/rosalloc.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/allocator/rosalloc.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/collector_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/collector_type.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/collector_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/collector_type.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/gc_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/collector/gc_type.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/gc_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/gc_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/collector/gc_type.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/mark_compact.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/collector/mark_compact.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/mark_compact.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/mark_compact.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/collector/mark_compact.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/space/region_space.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/space/region_space.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/space/region_space.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/region_space.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/space/region_space.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/space/space.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/space/space.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/space/space.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/space.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/space/space.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/gc/weak_root_state.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/gc/weak_root_state.h > ${MDVM_GENSRC_DIR}/art/runtime/gc/weak_root_state.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/weak_root_state.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: gc/weak_root_state.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/image.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/image.h > ${MDVM_GENSRC_DIR}/art/runtime/image.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/image.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: image.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/instrumentation.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/instrumentation.h > ${MDVM_GENSRC_DIR}/art/runtime/instrumentation.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/instrumentation.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: instrumentation.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/indirect_reference_table.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/indirect_reference_table.h > ${MDVM_GENSRC_DIR}/art/runtime/indirect_reference_table.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/indirect_reference_table.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: indirect_reference_table.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/jdwp_provider.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/jdwp_provider.h > ${MDVM_GENSRC_DIR}/art/runtime/jdwp_provider.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jdwp_provider.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: jdwp_provider.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/jni_id_type.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/jni_id_type.h > ${MDVM_GENSRC_DIR}/art/runtime/jni_id_type.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni_id_type.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: jni_id_type.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/linear_alloc.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/linear_alloc.h > ${MDVM_GENSRC_DIR}/art/runtime/linear_alloc.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/linear_alloc.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: linear_alloc.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/lock_word.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/lock_word.h > ${MDVM_GENSRC_DIR}/art/runtime/lock_word.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/lock_word.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: lock_word.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/oat.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/oat.h > ${MDVM_GENSRC_DIR}/art/runtime/oat.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: oat.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/oat_file.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/oat_file.h > ${MDVM_GENSRC_DIR}/art/runtime/oat_file.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_file.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: oat_file.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/process_state.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/process_state.h > ${MDVM_GENSRC_DIR}/art/runtime/process_state.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/process_state.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: process_state.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/reflective_value_visitor.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/reflective_value_visitor.h > ${MDVM_GENSRC_DIR}/art/runtime/reflective_value_visitor.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/reflective_value_visitor.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: reflective_value_visitor.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/stack.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/stack.h > ${MDVM_GENSRC_DIR}/art/runtime/stack.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/stack.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: stack.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/suspend_reason.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/suspend_reason.h > ${MDVM_GENSRC_DIR}/art/runtime/suspend_reason.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/suspend_reason.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: suspend_reason.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/thread.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/thread.h > ${MDVM_GENSRC_DIR}/art/runtime/thread.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: thread.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/thread_state.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/thread_state.h > ${MDVM_GENSRC_DIR}/art/runtime/thread_state.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread_state.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: thread_state.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/trace.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/trace.h > ${MDVM_GENSRC_DIR}/art/runtime/trace.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/trace.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: trace.h"
    VERBATIM)
add_custom_command(
    OUTPUT ${MDVM_GENSRC_DIR}/art/runtime/verifier/verifier_enums.h.operator_out.cc
    COMMAND ${CMAKE_COMMAND} -E make_directory ${MDVM_GENSRC_DIR}/art/runtime
    COMMAND ${Python3_EXECUTABLE} ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py art/runtime art/runtime/verifier/verifier_enums.h > ${MDVM_GENSRC_DIR}/art/runtime/verifier/verifier_enums.h.operator_out.cc
    DEPENDS ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/generate_operator_out.py ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/verifier_enums.h
    WORKING_DIRECTORY ${MDVM_NATIVE_SRC_ROOT_DIR}
    COMMENT "gensrcs art_operator_srcs: verifier/verifier_enums.h"
    VERBATIM)

add_library(art SHARED
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/app_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/aot_class_linker.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/art_field.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/sdk_checker.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/art_method.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/backtrace_helper.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/barrier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/gc_visited_arena_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/locks.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/mem_map_arena_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/mutex.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/quasi_atomic.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/base/timing_logger.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/cha.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/class_linker.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/class_loader_context.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/class_root.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/class_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/common_throws.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/compat_framework.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/debug_print.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/debugger.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/dex/dex_file_annotations.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/dex_register_location.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/elf_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/exec_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/fault_handler.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/allocation_record.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/allocator/art-dlmalloc.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/allocator/rosalloc.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/bitmap.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/card_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/heap_bitmap.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/mod_union_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/remembered_set.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/accounting/space_bitmap.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/concurrent_copying.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/garbage_collector.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/immune_region.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/immune_spaces.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/mark_compact.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/mark_sweep.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/partial_mark_sweep.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/semi_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/collector/sticky_mark_sweep.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/gc_cause.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/heap.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/reference_processor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/reference_queue.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/scoped_gc_critical_section.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/bump_pointer_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/dlmalloc_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/image_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/large_object_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/malloc_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/region_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/rosalloc_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/space/zygote_space.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/task_processor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/gc/verification.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/handle.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/hidden_api.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/hprof/hprof.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/image.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/index_bss_mapping.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/indirect_reference_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/instrumentation.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/intern_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/interpreter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/interpreter_cache.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/interpreter_common.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/interpreter_switch_impl0.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/interpreter_switch_impl1.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/lock_count_data.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/shadow_frame.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/unstarted_runtime.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/java_frame_root_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/javaheapprof/javaheapsampler.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/debugger_interface.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/jit.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/jit_code_cache.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/jit_memory_region.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/profiling_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jit/profile_saver.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/check_jni.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/java_vm_ext.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/jni_env_ext.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/jni_id_manager.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/jni_internal.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/jni/local_reference_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/method_handles.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/metrics/reporter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/array.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/class.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/class_ext.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/dex_cache.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/emulated_stack_frame.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/executable.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/field.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/method.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/method_handle_impl.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/method_handles_lookup.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/method_type.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/object.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/stack_frame_info.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/stack_trace_element.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/string.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/throwable.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/mirror/var_handle.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/monitor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/monitor_objects_stack_visitor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native_bridge_art_interface.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native_stack_dump.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_DexFile.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_BaseDexClassLoader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_VMDebug.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_VMRuntime.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_VMStack.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/dalvik_system_ZygoteHooks.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_Class.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_Object.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_StackStreamFactory.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_String.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_StringFactory.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_System.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_Thread.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_Throwable.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_VMClassLoader.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_invoke_MethodHandle.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_invoke_MethodHandleImpl.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_ref_FinalizerReference.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_ref_Reference.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Array.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Constructor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Executable.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Field.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Method.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Parameter.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_lang_reflect_Proxy.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/java_util_concurrent_atomic_AtomicLong.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/libcore_io_Memory.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/libcore_util_CharsetUtils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/org_apache_harmony_dalvik_ddmc_DdmServer.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/org_apache_harmony_dalvik_ddmc_DdmVmInternal.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/sun_misc_Unsafe.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/native/jdk_internal_misc_Unsafe.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/non_debuggable_classes.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/nterp_helpers.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_file_assistant.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_file_assistant_context.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_file_manager.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/oat_quick_method_header.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/object_lock.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/offsets.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/parsed_options.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/plugin.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/quick_exception_handler.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/read_barrier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/reference_table.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/reflection.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/reflective_handle_scope.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/reflective_value_visitor.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_callbacks.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_common.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_image.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_intrinsics.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_options.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/scoped_thread_state_change.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/signal_catcher.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/stack.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/stack_map.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/startup_completed_task.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/string_builder_append.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread_list.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/ti/agent.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/trace.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/transaction.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/var_handles.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/vdex_file.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/class_verifier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/instruction_flags.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/method_verifier.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/reg_type.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/reg_type_cache.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/register_line.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verifier/verifier_deps.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/verify_object.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/well_known_classes.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/context.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/instruction_set_features.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/memcmp16.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/arm/instruction_set_features_arm.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/arm/registers_arm.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/arm64/instruction_set_features_arm64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/arm64/registers_arm64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/riscv64/instruction_set_features_riscv64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/riscv64/registers_riscv64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86/instruction_set_features_x86.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86/registers_x86.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/registers_x86_64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/entrypoint_utils.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/jni/jni_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/math_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_alloc_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_cast_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_deoptimization_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_dexcache_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_entrypoints_enum.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_field_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_fillarray_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_jni_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_lock_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_math_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_string_builder_append_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_thread_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_throw_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/entrypoints/quick/quick_trampoline_entrypoints.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/monitor_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/runtime_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/thread_linux.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/mterp/nterp.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/interpreter/mterp/nterp_impl.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/context_x86_64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/entrypoints_init_x86_64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/jni_entrypoints_x86_64.S
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/memcmp16_x86_64.S
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/quick_entrypoints_x86_64.S
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86_64/thread_x86_64.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/monitor_pool.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime/arch/x86/fault_handler_x86.cc
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/impl_x86_linux_or_android.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
        ${MDVM_GENSRC_DIR}/art/runtime/base/callee_save_type.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/base/locks.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/class_status.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/compilation_kind.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc_root.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator_type.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/allocator/rosalloc.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/collector_type.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/gc_type.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/collector/mark_compact.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/space/region_space.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/space/space.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/gc/weak_root_state.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/image.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/instrumentation.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/indirect_reference_table.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/jdwp_provider.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/jni_id_type.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/linear_alloc.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/lock_word.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/oat.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/oat_file.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/process_state.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/reflective_value_visitor.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/stack.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/suspend_reason.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/thread.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/thread_state.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/trace.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/runtime/verifier/verifier_enums.h.operator_out.cc
        ${MDVM_GENSRC_DIR}/art/asm/mterp/mterp_x86_64.S
)

target_include_directories(art
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/cmdline
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/cpp-define-generator
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/dlmalloc
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform_header_only
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartpalette/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/lzma/C
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativebridge/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libnativeloader/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/unwinding/libunwindstack/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libdexfile/external/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libprofile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/odrefresh/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libelffile
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/include
        PUBLIC ${MDVM_GENSRC_DIR}/art/asm/include
)

target_compile_options(art
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -fsanitize-address-use-after-return=never -Wno-unused-command-line-argument -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86
)

target_compile_definitions(art
        PUBLIC ART_DEFAULT_GC_TYPE_IS_CMS USE_D8_DESUGAR=1 ART_TARGET ART_TARGET_LINUX
        PRIVATE ART_BASE_ADDRESS=0x60000000 "ART_BASE_ADDRESS_MIN_DELTA=(-0x1000000)" ART_BASE_ADDRESS_MAX_DELTA=0x1000000 ART_STACK_OVERFLOW_GAP_arm=8192 ART_STACK_OVERFLOW_GAP_arm64=8192 ART_STACK_OVERFLOW_GAP_riscv64=8192 ART_STACK_OVERFLOW_GAP_x86=8192 ART_STACK_OVERFLOW_GAP_x86_64=8192 ART_FRAME_SIZE_LIMIT=1736
)

target_link_options(art PRIVATE -z max-page-size=0x200000)

target_link_libraries(art artpalette base log lz4 lzma nativebridge nativeloader sigchain unwindstack artbase dexfile profile z odrstatslog elffile)

set_source_files_properties(
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/impl_x86_linux_or_android.c
        PROPERTIES COMPILE_OPTIONS "-DSTACK_LINE_READER_BUFFER_SIZE=1024;-Wno-gnu-designator;-Wno-unused-variable")

set_source_files_properties(
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/filesystem.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/stack_line_reader.c
        ${MDVM_NATIVE_SRC_ROOT_DIR}/external/cpu_features/src/string_view.c
        PROPERTIES COMPILE_OPTIONS "-DSTACK_LINE_READER_BUFFER_SIZE=1024;-Wno-gnu-designator")

# Generated by bp2cmake from art_cc_binary "dalvikvm". Do not edit by hand.
# Port-policy decisions for this module live in //overlay/port_policy.py.

add_executable(dalvikvm
        ${MDVM_NATIVE_SRC_ROOT_DIR}/art/dalvikvm/dalvikvm.cc
)

target_include_directories(dalvikvm
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/libartbase
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libbase/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/fmtlib/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/logging/liblog/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/header_only_include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_jni
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/libnativehelper/include_platform_header_only
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/cmdline
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/tools/cpp-define-generator
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/external/dlmalloc
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/runtime
        PUBLIC ${MDVM_NATIVE_SRC_ROOT_DIR}/art/sigchainlib
)

target_compile_options(dalvikvm
        PRIVATE -fno-rtti -ggdb3 -Wall -Wextra -Wstrict-aliasing -fstrict-aliasing -Wunreachable-code -Wredundant-decls -Wshadow -Wunused -fvisibility=protected -Wimplicit-fallthrough -Wfloat-equal -Wint-to-void-pointer-cast -Wused-but-marked-unused -Wdeprecated -Wunreachable-code-break -Wunreachable-code-return -Wno-invalid-offsetof -Winconsistent-missing-override -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -fno-omit-frame-pointer -msse4.2 -mpopcnt -DART_ENABLE_CODEGEN_x86_64 -DART_ENABLE_CODEGEN_x86 -fPIC
)

target_link_options(dalvikvm PRIVATE -Wl,--export-dynamic -pie)

target_link_libraries(dalvikvm log nativehelper art sigchain)
